name: runyankore-ner
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10  # You can adjust this depending on your needs
  - pip
  - numpy
  - scipy
  - tqdm
  - scikit-learn
  - seqeval
  - pandas
  - matplotlib
  - tensorboard
  - pip:
      - torch>=1.10.0
      - transformers
      - datasets
